---
- name: Create a Database instance
  hosts: localhost
  tasks:
    - name: Get the info of the VPC for the instance
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": VPCLCL42837_FIRST
      register: vpc_info
    - name: Get the info of the VPC Subnet for the instance in AZ1
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          "tag:Name": DEPLOY00001
          vpc-id: "{{ vpc_info.vpcs[0].id}}"
      register: subnet_info1
    - name: Get the info of the VPC Subnet for the instance in AZ2
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          "tag:Name": DEPLOY00011
          vpc-id: "{{ vpc_info.vpcs[0].id}}"
      register: subnet_info11
    - name: Create a Security Group
      amazon.aws.ec2_group:
        name: VPCLCL42837_FIRST_MYSQL
        description: MYSQL access
        vpc_id: "{{ vpc_info.vpcs[0].id}}"
        rules:
          - proto: tcp
            ports:
              - 3306
            cidr_ip: 0.0.0.0/24
      register: sg_info
    - name: Create a Database Subnet Group
      amazon.aws.rds_subnet_group:
        state: present
        name: VPCLCL42837_FIRST_DB_SUB
        description: Subnets for the Php Database
        subnets:
          - "{{ subnet_info1.subnets[0].id}}"
          - "{{ subnet_info11.subnets[0].id}}"
        tags:
          Name: VPCLCL42837_FIRST_DB_SUB
      register: db_info
    - debug: { var: db_info }
    - name: Create MYSQL Database in AZ1
      amazon.aws.rds_instance:
        db_name: RDS_00001
        backup_retention_period: 0
        monitoring_interval: 0
        engine: mysql
        engine_version: 8.0.40
        multi_az: true
        publicly_accessible: false
        db_instance_identifier: Php-backup
        vpc_security_group_ids: "{{ sg_info.group_id}}"
        db_subnet_group_name: "{{ db_info.subnet_group.db_subnet_group_name }}"
        instance_type: db.t3.micro
        allocated_storage: 20
        master_user_password: "{{ password }}"
        master_username: "{{ dbUsername }}"
